var words = [
{text:'Frog', imgSrc:'images/animals/frog.jpg', audioSrc:'', category_id:'2'},
{text:'Whale', imgSrc:'images/animals/whale.jpg', audioSrc:'', category_id:'2'},
{text:'Monkey', imgSrc:'images/animals/monkey.jpg', audioSrc:'', category_id:'2'},
{text:'Owl', imgSrc:'images/animals/owl.jpg', audioSrc:'', category_id:'2'},
{text:'Snake', imgSrc:'images/animals/snake.jpg', audioSrc:'', category_id:'2'},
{text:'Lion', imgSrc:'images/animals/lion.jpg', audioSrc:'', category_id:'2'},
{text:'Tiger', imgSrc:'images/animals/tiger.jpg', audioSrc:'', category_id:'2'},
{text:'Elephant', imgSrc:'images/animals/elephant.jpg', audioSrc:'', category_id:'2'},
{text:'Giraffe', imgSrc:'images/animals/giraffe.jpg', audioSrc:'', category_id:'2'},
{text:'Mouse', imgSrc:'images/animals/mouse.jpg', audioSrc:'', category_id:'2'},
{text:'Peacock', imgSrc:'images/animals/peacock.jpg', audioSrc:'', category_id:'2'},
{text:'Goat', imgSrc:'images/animals/goat.jpg', audioSrc:'', category_id:'2'},

{text:'Mouth', imgSrc:'images/organs/mouth.jpg', audioSrc:'', category_id:'9'},
{text:'Face', imgSrc:'images/organs/face.jpg', audioSrc:'', category_id:'9'},
{text:'Nose', imgSrc:'images/organs/nose.jpg', audioSrc:'', category_id:'9'},
{text:'Ears', imgSrc:'images/organs/ears.jpg', audioSrc:'', category_id:'9'},
{text:'Hands', imgSrc:'images/organs/hands.jpg', audioSrc:'', category_id:'9'},
{text:'Foot', imgSrc:'images/organs/foot.jpg', audioSrc:'', category_id:'9'},
{text:'Arms', imgSrc:'images/organs/arms.jpg', audioSrc:'', category_id:'9'},
{text:'Tongue', imgSrc:'images/organs/tongue.jpg', audioSrc:'', category_id:'9'},
{text:'Teeth', imgSrc:'images/organs/teeth.jpg', audioSrc:'', category_id:'9'},
{text:'Eyes', imgSrc:'images/organs/eyes.jpg', audioSrc:'', category_id:'9'},

{text:'Mirror', imgSrc:'images/things/mirror.jpg', audioSrc:'', category_id:'11'},
{text:'Toy', imgSrc:'images/things/toy.jpg', audioSrc:'', category_id:'11'},
{text:'Scissor', imgSrc:'images/things/scissor.jpg', audioSrc:'', category_id:'11'},
{text:'Shoes', imgSrc:'images/things/shoes.jpg', audioSrc:'', category_id:'11'},
{text:'Key', imgSrc:'images/things/key.jpg', audioSrc:'', category_id:'11'},
{text:'Books', imgSrc:'images/things/books.jpg', audioSrc:'', category_id:'11'},
{text:'Clothes', imgSrc:'images/things/clothes.jpg', audioSrc:'', category_id:'11'},
{text:'Bag', imgSrc:'images/things/bag.jpg', audioSrc:'', category_id:'11'},
{text:'Lock', imgSrc:'images/things/lock.jpg', audioSrc:'', category_id:'11'},
{text:'Umbrella', imgSrc:'images/things/umbrella.jpg', audioSrc:'', category_id:'11'},

{text:'Autumn', imgSrc:'images/weather/autumn.jpg', audioSrc:'', category_id:'13'},
{text:'Rain', imgSrc:'images/weather/rain.jpg', audioSrc:'', category_id:'13'},
{text:'Spring', imgSrc:'images/weather/spring.jpg', audioSrc:'', category_id:'13'},
{text:'Summer', imgSrc:'images/weather/summer.jpg', audioSrc:'', category_id:'13'},
{text:'Winter', imgSrc:'images/weather/winter.jpg', audioSrc:'', category_id:'13'},

{text:'Clock', imgSrc:'images/time/clock.jpg', audioSrc:'', category_id:'14'},
{text:'Evening', imgSrc:'images/time/evening.jpg', audioSrc:'', category_id:'14'},
{text:'Morning', imgSrc:'images/time/morning.jpg', audioSrc:'', category_id:'14'},
{text:'Night', imgSrc:'images/time/night.jpg', audioSrc:'', category_id:'14'},
{text:'Noon', imgSrc:'images/time/noon.jpg', audioSrc:'', category_id:'14'}
]